### ISSUE TITLE
BUG : "Successful" Ruby source ingestion fails to reach destinations

### ISSUE THREAD

**Issue by tokengeek** [rudderlabs/rudder-sdk-ruby#10]
**Describe the bug**

We already have a working Javascript source and destinations and have been attempting to get a Ruby source to work. Thus far we haven't been able to get any events successfully to any destination.

The Ruby source is set to sync with both Postgres DB and Mixpanel destinations. There are no user transformations set up.

We have dropped in `rudder-sdk-ruby` to our existing Segment setup into our Rails application. All the existing calls via the SDK appear to work correctly. No errors are reported, raised, or logged.

In the Rudderstack UI, all the events are ingested with no mention of any failures.

Both destinations are reporting what looks like Javascript/Typescript errors, as if an internal transformation is failing.

* Postgres DB is reporting `Cannot read property 'toLowerCase' of undefined`
* Mixpanel is reporting `Invalid message type. Type assertion failed`

We added a webhook destination for testing later that also fails.

* Webhook is reporting `{"response":"Error in workflow","firstAttemptedAt":"2023-03-29T11:32:13.949Z","content-type":"text/html; charset=utf-8"}`

An example payload for these is:

```json
{
    "sentAt": "2023-03-29T11:32:13.258Z",
    "messages": [
        {
            "type": "track",
            "event": "Created Cloud SQL",
            "sentAt": "2023-03-29T11:32:11.718Z",
            "userId": "usr-devel",
            "channel": "server",
            "context": {
                "groupId": "acc-devel",
                "library": {
                    "name": "rudderanalytics-ruby",
                    "version": "2.0.1"
                }
            },
            "messageId": "192118cf-e631-40e4-a489-7a86ec170f09",
            "timestamp": "2023-03-29T11:32:11.718Z",
            "properties": {
                "account_id": "acc-devel",
                "actioner_id": "usr-devel"
            },
            "integrations": {
                "All": true
            }
        }
    ],
    "rudderId": "853ae90f-0351-424b-973e-a615e6487517",
    "json_size": 399,
    "messageId": "4ca3ba11-fd92-498e-afad-1b9b0c4caa42",
    "timestamp": "2023-03-29T11:32:12.034Z",
    "receivedAt": "2023-03-29T11:32:12.035Z",
    "request_ip": <removed>,
    "max_message_count": 100,
    "originalTimestamp": "2023-03-29T11:32:13.258Z"
}
```

I suspect this is actually something to do with the Ruby source rather than the SDK itself.

We used the test API (https://www.rudderstack.com/docs/api/test-api) to check the supported Mixpanel destination and that correctly worked. Testing the Ruby source with the test API also reported success for Mixpanel and Webhook:

```json
[
  {
    "destinationId": <removed>,
    "destinationName": "Postgres DB",
    "error": "Destination type not supported by Test API"
  },
  {
    "destinationId": <removed>,
    "destination": "MP",
    "destinationName": "Mixpanel Staging",
    "data": [
      {
        "user_transformed_payload": {
          "error": "Transformation VersionID not found"
        },
        "dest_transformed_payload": [
          {
            "version": "1",
            "type": "REST",
            "method": "POST",
            "endpoint": "https://api-eu.mixpanel.com/import/",
            "headers": {
              "Authorization": "Basic <removed>",
              "User-Agent": "RudderLabs"
            },
            "params": {
              "data": <removed>
            },
            "body": {
              "JSON": {},
              "JSON_ARRAY": {},
              "XML": {},
              "FORM": {}
            },
            "files": {},
            "userId": "usr-devel"
          }
        ],
        "destination_response": [
          1
        ],
        "destination_response_status": [
          200
        ]
      }
    ]
  },
  {
    "destinationId": <removed>,
    "destination": "WEBHOOK",
    "destinationName": "webhook test destination",
    "data": [
      {
        "user_transformed_payload": {
          "error": "Transformation VersionID not found"
        },
        "dest_transformed_payload": [
          {
            "version": "1",
            "type": "REST",
            "method": "POST",
            "endpoint": <removed>,
            "headers": {
              "content-type": "application/json",
              "User-Agent": "RudderLabs"
            },
            "params": {},
            "body": {
              "JSON": {
                "type": "track",
                "event": "Testing Ruby source",
                "userId": "usr-devel",
                "context": {
                  "groupId": "acc-devel",
                  "library": {
                    "name": "rudderanalytics-ruby",
                    "version": "2.0.1"
                  }
                },
                "properties": {
                  "account_id": "acc-devel",
                  "actioner_id": "usr-devel"
                },
                "integrations": {
                  "All": true
                }
              },
              "JSON_ARRAY": {},
              "XML": {},
              "FORM": {}
            },
            "files": {}
          }
        ],
        "destination_response": [
          {
            "about": "Pipedream is the fastest way to connects APIs. Build and run workflows with code-level control when you need it — and no code when you don't.",
            "event_id": <removed>,
            "workflow_id": <removed>,
            "owner_id": <removed>,
            "deployment_id": <removed>,
            "timestamp": "2023-03-29T10:42:19.172Z",
            "inspect": <removed>,
            "quickstart": "https://pipedream.com/quickstart/"
          }
        ],
        "destination_response_status": [
          200
        ]
      }
    ]
  }
]
```

Our existing Javascript pipeline has been working successfully for a while with the same destinations. The Testing API also appears to have worked.

Our existing Segment setup has also been working successfully as well and the SDK had been dropped in without reporting any failures.

So the problem seems to be the Ruby source is able to import but unable to successfully export to at least three different destinations.

This occurred yesterday when we set up integration.

**To Reproduce**
Steps to reproduce the behaviour:

1. Set up a Ruby source
2. Set up a Postgres DB destination
3. Set up a Mixpanel destination
4. Connect Ruby source to both destinations
5. Send a tracking event via the SDK to Ruby source
6. Ruby source shows event is successfully ingested
7. Postgres DB destination reports a failure: Error code 400 - Cannot read property 'toLowerCase' of undefined
8. Mixpanel destination reports a failure: Error code 400 - Invalid message type. Type assertion failed

**Expected behavior**

1. A successfully imported event with no custom transformation rules should successfully sync with all destinations.
2. If the source events are incorrect, they should not report as successfully ingested.
3. If the source events are incorrect, they should be stopped by the SDK before sending.

**Version of the _Ruby_**

Ruby 2.3 and 3.1 have been used for testing.

**Version of the _Rudder Ruby_ SDK**

Upgraded to v2.0.1 but was present on a patched v2.0.0

**SDK initialisation snippet**

Gemfile includes `gem "rudder-sdk-ruby", ">= 2.0.1"`

Rails application

```ruby
  def self.track(user_id, event, properties = {})
    return unless App.config.analytics_enabled?

    analytics = if App.config.rudderstack_enabled?
                  Rudder::Analytics.new(
                    write_key: App.config.rudderstack_write_key,
                    data_plane_url: App.config.rudderstack_data_plane_uri,
                    on_error: proc { |error_code, error_body|
                      Rails.logger.info "[analytics] #{error_code} #{error_body}"
                    }
                  )
                else
                  Segment::Analytics.new(write_key: App.config.segment_io_write_key)
                end

    tracking_data = {
      user_id: user_id,
      event: event,
      properties: properties
    }

    account_id = properties.fetch(:account_id, nil)
    if account_id
      tracking_data[:context] = {
        groupId: account_id
      }
    end

    analytics.track(tracking_data)
  end
```

**Check for Correct Usage of _writeKey_ and _dataPlaneUrl_**

We are not receiving any warnings about bad credentials.
The Ruby source is showing hundreds of ingested events with no failures.

**Comment by pallabmaiti** [comment]
Hey @tokengeek the issue is fixed?

**Comment by tokengeek** [comment]
I'll try to make some time to update and re-test in the next week or two using the latest version of the SDK.

We had to remove the code as it was not working for us so we need to reapply all the changes from 6 months ago to re-test.

**Comment by tokengeek** [comment]
I re-enabled our application to use Rudderstack and updated to v2.0.3. Turns out it was disabled and not reverted so it was easier than I expected.

The events were still able to be ingested as before but this time, the Ruby source was able to deliver to our Postgres and Mixpanel destinations without reporting failures during the back-end transformation.

So the server side issues seem to be resolved now. The client code did not change with the exception of updating to the latest version of the SDK.
