### ISSUE TITLE
BUG : Unguarded `require "pry"` causes `LoadError` unless `pry` is available

### ISSUE THREAD

**Issue by tokengeek** [rudderlabs/rudder-sdk-ruby#8]
**Describe the bug**

In `Rudder::Analytics::Transport`, there is a `require "pry"` line that presupposes that `pry` is available to the application.

https://github.com/rudderlabs/rudder-sdk-ruby/blob/b4e5319e3d4fca5b88068eea172ea63cd4f85625/lib/rudder/analytics/transport.rb#L11

If `pry` is not present in the Bundler group then requiring `rudder` will raise a `LoadError`.

```
> bundle exec ruby pry_test.rb
.../vendor/ruby/3.1.0/gems/rudder-sdk-ruby-2.0.0/lib/rudder/analytics/transport.rb:11:in `require': cannot load such file -- pry (LoadError)
Did you mean?  pty
...
```

We have `pry` in our development/test Bundler groups but not in production. So attempting to deploy with Capistrano or start a Rails server in production mode raises the error.

**To Reproduce**
Steps to reproduce the behaviour:

Create the following files in a directory...

```
# Gemfile
source "https://rubygems.org"

gem "rudder-sdk-ruby"
```

```
# pry_test.rb
require "rudder"
```

Use bundler to run the script.

```
> bundle install
> bundle exec ruby pry_test.rb
```

**Expected behavior**

The gem should load without causing any problems in this minimal test case.

Either the `LoadError`  needs rescuing around `require "pry"` or it should be removed and only added by developers as and when required.

**Version of the _Ruby_**

Tested and fails on Ruby 2.3 and 3.1

**Version of the _Rudder Ruby_ SDK**

Version 2.0.0

**Comment by pallabmaiti** [comment]
Thanks, @tokengeek. We will look into it.
